### ISSUE TITLE
Please add visual indicator for when muted

### ISSUE THREAD

**Issue by rutgerrrrr** [gbl/Silence#1]
Hi!

I love this mod, it's exactly what I wanted for a while now! The only thing I feel that is missing, is a visual indicator to let me know if the game is muted or not. Maybe some icon in the a corner of the screen or something like that, similar as to "[Simple Voice Chat](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/)" does it.

For example: [https://i.imgur.com/NTzjYcf.png](https://i.imgur.com/NTzjYcf.png)

**Comment by gbl** [comment]
That's a very nice idea. Just pushed to Curseforge and Modrinth (in the 1.17.1 version; the 1.18 version will get that feature with the next snapshot)

**Comment by danielwerg** [comment]
It would look more elegant if you remove grass block background.
